import { Chef } from "./chefProps.interface";
import { photo } from "./photos.constant";

export const allChefsData: Chef[] = [
  {
    id: "1",
    name: "Guilherme Berté",
    cuisine: "French Cuisine",
    rating: 4.7,
    distance: 2.5,
    image: photo.chef1,
    priceRange: "$$$",
    IsFavorite: true
  },
  {
    id: "2",
    name: "Helena de Brito ",
    cuisine: "Mexican Traditional",
    rating: 4.9,
    distance: 3.1,
    image: photo.chefa1,
    priceRange: "$$",
    IsFavorite: true
  },
  {
    id: "3",
    name: "Gustavo Andrade ",
    cuisine: "Mexican Traditional",
    rating: 4.7,
    distance: 2.5,
    image: photo.chef2,
    priceRange: "$$",
    IsFavorite: true
  },
  {
    id: "4",
    name: "Maria Antonia",
    cuisine: "Italian Contemporary",
    rating: 4.8,
    distance: 4.2,
    image: photo.chefa2,
    priceRange: "$$$$",
    IsFavorite: false,
  },
  {
    id: "5",
    name: "Isabela Finocchi",
    cuisine: "Japanese Sushi",
    rating: 4.6,
    distance: 0.9,
    image: photo.chefa3,
    priceRange: "$$",
    IsFavorite: false,
  },
  {
    id: "6",
    name: "Maria Antonia",
    cuisine: "Brazilian Regional",
    rating: 5.0,
    distance: 3.5,
    image: photo.chefa4,
    priceRange: "$",
    IsFavorite: false,
  },
  {
    id: "7",
    name: "Sofia Crepaldi",
    cuisine: "French Cuisine",
    rating: 4.7,
    distance: 2.1,
    image: photo.chefa5,
    priceRange: "$$$$",
    IsFavorite: false,
  },
  {
    id: "8",
    name: "Pierre Real",
    cuisine: "Moroccan Delights",
    rating: 4.4,
    distance: 5.0,
    image: photo.chef3,
    priceRange: "$$",
    IsFavorite: false,
  },
  {
    id: "9",
    name: "Hiroshi Tanaka",
    cuisine: "Japanese Sushi",
    rating: 4.9,
    distance: 1.5,
    image: photo.chef4,
    priceRange: "$$$$$",
    IsFavorite: false,
  },
  {
    id: "10",
    name: "Daniel Fierri",
    cuisine: "Mediterranean Fresh",
    rating: 4.6,
    distance: 2.8,
    image: photo.chef5,
    priceRange: "$$$",
    IsFavorite: false,
  },
  {
    id: "11",
    name: "Raphael Santos",
    cuisine: "American Comfort",
    rating: 4.3,
    distance: 6.1,
    image: photo.chef6,
    priceRange: "$$",
    IsFavorite: false,
  },
  {
    id: "12",
    name: "Sofia Petrov",
    cuisine: "Eastern European",
    rating: 4.7,
    distance: 3.9,
    image: photo.chefa6,
    priceRange: "$",
    IsFavorite: false,
  },
  {
    id: "13",
    name: "Antonio Morales",
    cuisine: "Spanish Tapas",
    rating: 4.8,
    distance: 0.7,
    image: photo.chef7,
    priceRange: "$$$",
    IsFavorite: false,
  },
  {
    id: "14",
    name: "Lena Schmidt",
    cuisine: "German Modern",
    rating: 4.2,
    distance: 4.5,
    image: photo.chefa7,
    priceRange: "$$",
    IsFavorite: false,
  },
  {
    id: "15",
    name: "Omar Hassan",
    cuisine: "Middle Eastern",
    rating: 4.5,
    distance: 1.2,
    image: photo.chef8,
    priceRange: "$$",
    IsFavorite: false,
  },
  {
    id: "16",
    name: "Chloe Dubois",
    cuisine: "Vegan & Organic",
    rating: 4.9,
    distance: 2.3,
    image: photo.chefa8,
    priceRange: "$$$",
    IsFavorite: false,
  },
  {
    id: "17",
    name: "Rohan Sharma",
    cuisine: "Indian Spicy",
    rating: 4.6,
    distance: 5.8,
    image: photo.chef9,
    priceRange: "$",
    IsFavorite: false,
  },
  {
    id: "18",
    name: "Elena Petrova",
    cuisine: "Russian Home",
    rating: 4.1,
    distance: 3.0,
    image: photo.chefa9,
    priceRange: "$",
    IsFavorite: false,
  },
  {
    id: "19",
    name: "Javier Gomez",
    cuisine: "Peruvian Nikkei",
    rating: 5.0,
    distance: 0.5,
    image: photo.chef10,
    priceRange: "$$$$$",
    IsFavorite: false,
  },
  {
    id: "20",
    name: "Sophie Müller",
    cuisine: "Swiss Fine Dining",
    rating: 4.8,
    distance: 2.7,
    image: photo.chef10,
    priceRange: "$$$$",
    IsFavorite: false,
  },
];

export default allChefsData