export const photo = {
  chefIA: 'https://mmdbbucket.s3.sa-east-1.amazonaws.com/chefia.jpg',
  berte: 'https://mmdbbucket.s3.sa-east-1.amazonaws.com/berte.png',
  chef1: 'https://mmdbbucket.s3.sa-east-1.amazonaws.com/chef1.png',
  chef2: 'https://mmdbbucket.s3.sa-east-1.amazonaws.com/chef2.png',
  chef3: 'https://mmdbbucket.s3.sa-east-1.amazonaws.com/chef3.png',
  chef4: 'https://mmdbbucket.s3.sa-east-1.amazonaws.com/chef4.png',
  chef5: 'https://mmdbbucket.s3.sa-east-1.amazonaws.com/chef5.png',
  chef6: 'https://mmdbbucket.s3.sa-east-1.amazonaws.com/chef6.png',
  chef7: 'https://mmdbbucket.s3.sa-east-1.amazonaws.com/chef7.png',
  chef8: 'https://mmdbbucket.s3.sa-east-1.amazonaws.com/chef8.png',
  chef9: 'https://mmdbbucket.s3.sa-east-1.amazonaws.com/chef9.png', 
  chef10: 'https://mmdbbucket.s3.sa-east-1.amazonaws.com/chef10.png',
  chefa1: 'https://mmdbbucket.s3.sa-east-1.amazonaws.com/chefa1.png',
  chefa2: 'https://mmdbbucket.s3.sa-east-1.amazonaws.com/chefa2.png',
  chefa3: 'https://mmdbbucket.s3.sa-east-1.amazonaws.com/chefa3.png',
  chefa4: 'https://mmdbbucket.s3.sa-east-1.amazonaws.com/chefa4.png',
  chefa5: 'https://mmdbbucket.s3.sa-east-1.amazonaws.com/chefa5.png',
  chefa6: 'https://mmdbbucket.s3.sa-east-1.amazonaws.com/chefa6.png',
  chefa7: 'https://mmdbbucket.s3.sa-east-1.amazonaws.com/chefa7.png',
  chefa8: 'https://mmdbbucket.s3.sa-east-1.amazonaws.com/chefa8.png',
  chefa9: 'https://mmdbbucket.s3.sa-east-1.amazonaws.com/chefa9.png',
  chefa10: 'https://mmdbbucket.s3.sa-east-1.amazonaws.com/chefa10.png',
}