import { Chef } from './../components/chefsCard/chefProps.interface';
export const allChefsData: Chef[] = [
  {
    id: '1',
    name: 'James Wilson',
    cuisine: 'French Cuisine',
    rating: 4.7,
    distance: 2.5,
    image: 'https://randomuser.me/api/portraits/men/1.jpg',
  },
  {
    id: '2',
    name: 'Maria Garcia',
    cuisine: 'Mexican Traditional',
    rating: 4.9,
    distance: 3.1,
    image: 'https://randomuser.me/api/portraits/women/2.jpg',
  },
  {
    id: '3',
    name: 'Chen Li',
    cuisine: 'Asian Fusion',
    rating: 4.5,
    distance: 1.8,
    image: 'https://randomuser.me/api/portraits/men/3.jpg',
  },
  {
    id: '4',
    name: 'Sophia Rossi',
    cuisine: 'Italian Contemporary',
    rating: 4.8,
    distance: 4.2,
    image: 'https://randomuser.me/api/portraits/women/4.jpg',
  },
  {
    id: '5',
    name: 'David Kim',
    cuisine: 'Korean BBQ',
    rating: 4.6,
    distance: 0.9,
    image: 'https://randomuser.me/api/portraits/men/5.jpg',
  },
  {
    id: '6',
    name: 'Ana Silva',
    cuisine: 'Brazilian Regional',
    rating: 5.0,
    distance: 3.5,
    image: 'https://randomuser.me/api/portraits/women/6.jpg',
  },
  {
    id: '7',
    name: 'Pierre Dubois',
    cuisine: 'French Cuisine',
    rating: 4.7,
    distance: 2.1,
    image: 'https://randomuser.me/api/portraits/men/7.jpg',
  },
  {
    id: '8',
    name: 'Fatima Zahra',
    cuisine: 'Moroccan Delights',
    rating: 4.4,
    distance: 5.0,
    image: 'https://randomuser.me/api/portraits/women/8.jpg',
  },
  {
    id: '9',
    name: 'Hiroshi Tanaka',
    cuisine: 'Japanese Sushi',
    rating: 4.9,
    distance: 1.5,
    image: 'https://randomuser.me/api/portraits/men/9.jpg',
  },
  {
    id: '10',
    name: 'Isabella Costa',
    cuisine: 'Mediterranean Fresh',
    rating: 4.6,
    distance: 2.8,
    image: 'https://randomuser.me/api/portraits/women/10.jpg',
  },
  {
    id: '11',
    name: 'Mark Johnson',
    cuisine: 'American Comfort',
    rating: 4.3,
    distance: 6.1,
    image: 'https://randomuser.me/api/portraits/men/11.jpg',
  },
  {
    id: '12',
    name: 'Sofia Petrov',
    cuisine: 'Eastern European',
    rating: 4.7,
    distance: 3.9,
    image: 'https://randomuser.me/api/portraits/women/12.jpg',
  },
  {
    id: '13',
    name: 'Antonio Morales',
    cuisine: 'Spanish Tapas',
    rating: 4.8,
    distance: 0.7,
    image: 'https://randomuser.me/api/portraits/men/13.jpg',
  },
  {
    id: '14',
    name: 'Lena Schmidt',
    cuisine: 'German Modern',
    rating: 4.2,
    distance: 4.5,
    image: 'https://randomuser.me/api/portraits/women/14.jpg',
  },
  {
    id: '15',
    name: 'Omar Hassan',
    cuisine: 'Middle Eastern',
    rating: 4.5,
    distance: 1.2,
    image: 'https://randomuser.me/api/portraits/men/15.jpg',
  },
  {
    id: '16',
    name: 'Chloe Dubois',
    cuisine: 'Vegan & Organic',
    rating: 4.9,
    distance: 2.3,
    image: 'https://randomuser.me/api/portraits/women/16.jpg',
  },
  {
    id: '17',
    name: 'Rohan Sharma',
    cuisine: 'Indian Spicy',
    rating: 4.6,
    distance: 5.8,
    image: 'https://randomuser.me/api/portraits/men/17.jpg',
  },
  {
    id: '18',
    name: 'Elena Petrova',
    cuisine: 'Russian Home',
    rating: 4.1,
    distance: 3.0,
    image: 'https://randomuser.me/api/portraits/women/18.jpg',
  },
  {
    id: '19',
    name: 'Javier Gomez',
    cuisine: 'Peruvian Nikkei',
    rating: 5.0,
    distance: 0.5,
    image: 'https://randomuser.me/api/portraits/men/19.jpg',
  },
  {
    id: '20',
    name: 'Sophie Müller',
    cuisine: 'Swiss Fine Dining',
    rating: 4.8,
    distance: 2.7,
    image: 'https://randomuser.me/api/portraits/women/20.jpg',
  },
];